/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visual;

import javax.swing.JOptionPane;

/**
 *
 * @author Thiago
 */
public class Triage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Triage
     */
    public Triage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboRespiracion = new javax.swing.JComboBox<>();
        cboPulso = new javax.swing.JComboBox<>();
        cboEstadoMental = new javax.swing.JComboBox<>();
        cboConciencia = new javax.swing.JComboBox<>();
        cboDolorPecho = new javax.swing.JComboBox<>();
        cboLesionesGraves = new javax.swing.JComboBox<>();
        cboEdad = new javax.swing.JComboBox<>();
        cboFiebre = new javax.swing.JComboBox<>();
        cboVomitos = new javax.swing.JComboBox<>();
        cboDolorAbominal = new javax.swing.JComboBox<>();
        cboSignosShock = new javax.swing.JComboBox<>();
        cboLesionesLeves = new javax.swing.JComboBox<>();
        cboSangrado = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Triage");

        jLabel1.setText("Respiracion");

        jLabel2.setText("Estado Mental");

        jLabel3.setText("Pulso");

        jLabel4.setText("Conciencia");

        jLabel5.setText("Dolor de Pecho/Dif resp");

        jLabel6.setText("Lesiones Graves");

        jLabel7.setText("Edad");

        jLabel8.setText("Fiebre");

        jLabel9.setText("Vomitos");

        jLabel10.setText("Dolor Abdominal");

        jLabel11.setText("Signos de Shock");

        jLabel12.setText("Lesiones Leves");

        jLabel13.setText("Sangrado");

        cboRespiracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Normal", "Dificultad respiratoria moderada", "Dificultad respiratoria grave" }));

        cboPulso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Normal", "Anormal" }));

        cboEstadoMental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Normal", "Confusion leve", "Confusion grave" }));

        cboConciencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Conciente y alerta", "Perdida de conciencia" }));
        cboConciencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboConcienciaActionPerformed(evt);
            }
        });

        cboDolorPecho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "No presente", "Presente" }));

        cboLesionesGraves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "No presentes", "Presentes" }));

        cboEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Adulto", "Niño o anciano" }));
        cboEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEdadActionPerformed(evt);
            }
        });

        cboFiebre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sin fiebre", "Fiebre moderada", "Fiebre alta" }));

        cboVomitos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sin vomitos", "Vomitos moderados", "Vomitos intensos" }));
        cboVomitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVomitosActionPerformed(evt);
            }
        });

        cboDolorAbominal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "No presente", "Dolor abdominal moderado", "Dolor abdominal severo" }));

        cboSignosShock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "No presentes", "Presentes" }));

        cboLesionesLeves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "No presentes", "Presentes" }));

        cboSangrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "No presente", "Sangrado moderado", "Sangrado intenso" }));
        cboSangrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSangradoActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cboDolorPecho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(64, 64, 64)
                                .addComponent(cboLesionesLeves, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(60, 60, 60)
                                .addComponent(cboDolorAbominal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(107, 107, 107)
                                .addComponent(cboVomitos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(117, 117, 117)
                                .addComponent(cboFiebre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(123, 123, 123)
                                .addComponent(cboEdad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(58, 58, 58)
                                .addComponent(cboLesionesGraves, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(90, 90, 90)
                                .addComponent(cboConciencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(74, 74, 74)
                                .addComponent(cboEstadoMental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboPulso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboRespiracion, 0, 239, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(59, 59, 59)
                                .addComponent(cboSignosShock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(98, 98, 98)
                                .addComponent(cboSangrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(177, 177, 177))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboRespiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPulso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEstadoMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboConciencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDolorPecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLesionesGraves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFiebre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboVomitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboDolorAbominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboSignosShock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboLesionesLeves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboSangrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void capturar(Clases_Entidades.Triage Pac){
        Pac.setRespiracion(cboRespiracion.getSelectedItem().toString());
        Pac.setPulso(cboPulso.getSelectedItem().toString());
        Pac.setEstadoMental(cboEstadoMental.getSelectedItem().toString());
        Pac.setConciencia(cboConciencia.getSelectedItem().toString());
        Pac.setDolorPecho(cboDolorPecho.getSelectedItem().toString());
        Pac.setLesionesGraves(cboLesionesGraves.getSelectedItem().toString());
        Pac.setEdad(cboEdad.getSelectedItem().toString());
        Pac.setFiebre(cboFiebre.getSelectedItem().toString());
        Pac.setVomitos(cboVomitos.getSelectedItem().toString());
        Pac.setDolorAbdominal(cboDolorAbominal.getSelectedItem().toString());
        Pac.setSignosShock(cboSignosShock.getSelectedItem().toString());
        Pac.setLesionesLeves(cboLesionesLeves.getSelectedItem().toString());
        Pac.setSangrado(cboSangrado.getSelectedItem().toString());
    }
    public int sumar (Clases_Entidades.Triage a ){
        int contador = 0;
        switch (cboRespiracion.getSelectedItem().toString()){
            case "Normal":
                break;
            case "Dificultad respiratoria moderada":
                contador+=1;
                break;
            case "Dificultad respiratoria grave":
                contador+=2;
                break;      
        }
        
        if(cboPulso.getSelectedItem().toString() == "Anormal"){
            contador+=1;
        }
        
        switch (cboEstadoMental.getSelectedItem().toString()){
            case "Normal":
                break;
            case "Confusion Leve":
                contador+=1;
                break;
            case "Confusion Grave":
                contador+=2;
                break;      
        }
        
        if(cboConciencia.getSelectedItem().toString() == "Perdida de conciencia"){
            contador+=3;
        }
        
        if(cboDolorPecho.getSelectedItem().toString() == "Presente"){
            contador+=1;
        }
        
        if(cboLesionesGraves.getSelectedItem().toString() == "Presentes"){
            contador+=2;
        }
        
        if(cboEdad.getSelectedItem().toString() == "Niño o Anciano"){
            contador+=1;
        }
        
        switch (cboFiebre.getSelectedItem().toString()){
            case "Sin Fiebre":
                break;
            case "Fiebre moderada":
                contador+=1;
                break;
            case "Fiebre alta":
                contador+=2;
                break;      
        }
        
        switch (cboVomitos.getSelectedItem().toString()){
            case "Sin vomitos":
                break;
            case "Vomitos moderados":
                contador+=1;
                break;
            case "Vomitos intesos":
                contador+=2;
                break;      
        }
        
        switch (cboDolorAbominal.getSelectedItem().toString()){
            case "No presente":
                break;
            case "Dolor abdominal moderado":
                contador+=1;
                break;
            case "Dolor abdominal severo":
                contador+=2;
                break;      
        }
        
        if(cboSignosShock.getSelectedItem().toString() == "Presentes"){
            contador+=3;
        }
        
        if(cboLesionesLeves.getSelectedItem().toString() == "Presentes"){
            contador+=1;
        }
        
        switch (cboSangrado.getSelectedItem().toString()){
            case "No presente":
                break;
            case "Sangrado moderado":
                contador+=1;
                break;
            case "Sangrado intenso":
                contador+=2;
                break;      
        }
        return contador;
    }
    private void cboEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEdadActionPerformed

    private void cboConcienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboConcienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboConcienciaActionPerformed

    private void cboVomitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVomitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVomitosActionPerformed

    private void cboSangradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSangradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSangradoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cboRespiracion.setSelectedIndex(0);
        cboPulso.setSelectedIndex(0);
        cboEstadoMental.setSelectedIndex(0);
        cboConciencia.setSelectedIndex(0);
        cboDolorPecho.setSelectedIndex(0);
        cboLesionesGraves.setSelectedIndex(0);
        cboEdad.setSelectedIndex(0);
        cboFiebre.setSelectedIndex(0);
        cboVomitos.setSelectedIndex(0);
        cboDolorAbominal.setSelectedIndex(0);
        cboSignosShock.setSelectedIndex(0);
        cboLesionesLeves.setSelectedIndex(0);
        cboSangrado.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        Clases_Entidades.Triage a = new Clases_Entidades.Triage();
        int contador = 0;
        String color = "";
        
        
        this.capturar(a);
        
        
        contador = this.sumar(a);
        
             
        if(contador >= 0 && contador <= 4 ){
            color = "Verde";   
        } 
        else if (contador >= 5 && contador <= 9  ){
            color = "Amarillo";
        }
        else if (contador >=10 && contador <= 14){
            color = "Naranja";
        }
        else if (contador >= 15){
            color = "Rojo";
        }
   
        
        JOptionPane.showMessageDialog(this, "se ah guardado con exito \n" + a.toString() + "\n El nivel de atencion es de " + color.toUpperCase());
        
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboConciencia;
    private javax.swing.JComboBox<String> cboDolorAbominal;
    private javax.swing.JComboBox<String> cboDolorPecho;
    private javax.swing.JComboBox<String> cboEdad;
    private javax.swing.JComboBox<String> cboEstadoMental;
    private javax.swing.JComboBox<String> cboFiebre;
    private javax.swing.JComboBox<String> cboLesionesGraves;
    private javax.swing.JComboBox<String> cboLesionesLeves;
    private javax.swing.JComboBox<String> cboPulso;
    private javax.swing.JComboBox<String> cboRespiracion;
    private javax.swing.JComboBox<String> cboSangrado;
    private javax.swing.JComboBox<String> cboSignosShock;
    private javax.swing.JComboBox<String> cboVomitos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
